### ISSUE TITLE
Feature request: extra option for manipulating classes on the button and its icon

### ISSUE THREAD

**Issue by lolmaus** [dockyard/ember-cli-async-button#22]
Hi! Thank you for the awesome addon!

Before i started using it, i tried [ember-idx-button](https://github.com/indexiatech/ember-idx-button). That addon appeared to be buggy, so i abandoned it in favor of ember-cli-async-button.

But ember-idx-button had a couple of awesome features that ember-cli-async-button is missing.

# 1. Options to assign custom classes depending on the state

This feature is irreplaceable for people using non-semantic CSS frameworks like Bootstrap and Foundation.

Instead of writing custom CSS to style different button states, we could simply tell which classes to use in which state:

```
      {{ async-button
        action="saveSelection"
        class="btn btn-lg"

        default="Save"
        defaultClass='btn-primary'

        pending="Saving..."
        pendingClass='btn-default'

        rejected="Save failed :("
        rejectedClass='btn-danger'
      }}
```

# 2. Built in icon functionality

We could provide options similar to suggested above. When these new options are set, the component would render an additional `<i>` element inside and apply mentioned classes to it.

```
      {{ async-button
        action="saveSelection"
        class="btn btn-lg"

        default="Save"
        defaultIcon='glyphicon glyphicon-refresh'

        pending="Saving..."
        pendingIcon='glyphicon glyphicon-refresh glyphicon-spinning'

        rejected="Save failed :("
        rejectedIcon='glyphicon glyphicon-warning-sign'
      }}
```

Example pending state:

```html
<button ... >
  <i class="glyphicon glyphicon-refresh glyphicon-spinning"></i>
  Saving...
</button>
```

**Comment by lolmaus** [comment]
If you agree with the idea of this request, i might *try* to make a pull request. Can't give you a promise (pun not intended) because i'm short on both time and skill. But if i do find time, i'll be happy to try. Need a green light from you.

**Comment by danmcclain** [comment]
Around 2, we actually bound pending to a property on our controller before to do something similar (using your example)

Controller:
```js
export default Ember.Controller.extend({
  pendingState: '<i class="glyphicon glyphicon-refresh glyphicon-spinning"></i> Saving...'
})
```

```hbs
{{async-button pending=pendingState}}
```

**Comment by lolmaus** [comment]
@danmcclain, thank you for your contribution! It's a nice workaround, that is you can already use it with the addon.

But it requires a lot of boilerplate code: you have to duplicate icon HTML for every button type you use: three icons for save button, three more icons for refresh button, another three icons for delete button, etc. And if you want to customize the text of a button, you'll have to do even more copy-pasting.

Of course, you could use computed properties to get rid of copy-pasted HTML, but it still means huge amounts of boilerplate code.

Thus, the feature request.

**Comment by danmcclain** [comment]
I'm not sure this would be necessary for async button, as you can create your own copy of async button. I added the icon example in [the component](https://github.com/danmcclain/custom-async-button-example/blob/master/app/components/new-async-button.js) and [its template](https://github.com/danmcclain/custom-async-button-example/blob/master/app/templates/components/new-async-button.hbs).  It would be arbitrary to add the class example that you describe as well. Where it is simple to add these by creating your own copy of the button within your app, I vote on keeping it separate from ember-cli-async-button. @bcardarella Thoughts?

**Comment by bcardarella** [comment]
Async button should already be setting the `textState` as a class binding: https://github.com/dockyard/ember-cli-async-button/blob/master/app/components/async-button.js#L8

**Comment by bcardarella** [comment]
but if you are looking to override with your own you can probably just do:

```handlebars
{{async-button class=btnState}}
```

then just have `btnState` be a CP that returns a value for whatever the current value of `textState` is
