### ISSUE TITLE
False positive tests

### ISSUE THREAD

**Issue by lolmaus** [dockyard/ember-cli-async-button#24]
Tests in question: ["button bound to controller promise hidden on resolve"](https://github.com/dockyard/ember-cli-async-button/blob/master/tests/acceptance/button-test.js#L59) and ["button bound to controller promise hidden on reject"](https://github.com/dockyard/ember-cli-async-button/blob/master/tests/acceptance/button-test.js#L80).

Each of them only tests for `controller.set("promise", promise)` which is happening in the test itself. Commenting out the `resolve()` and `reject()` lines does not affect test success.

I'm not sure what they were supposed to test (the template binds `controller.promise` to the component's `boundPromise` property, but that property is not used anywhere), so i'm unable to provide a PR.

**Comment by lolmaus** [comment]
If #23 gets merged before you fix this, please follow #23's conventions: reuse `AppController`, flatten out promises, use `andThen` instead of `Ember.run.later`.

**Comment by lolmaus** [comment]
I can try fixing the tests if you explain me what they are supposed to test.

**Comment by bcardarella** [comment]
The PR that added the tests is here: https://github.com/dockyard/ember-cli-async-button/commit/628c52eebd58e3bd346007a1e11c836c780a9880

the author @ernesto-jimenez might be the best to ask the intent

**Comment by lolmaus** [comment]
Hmm, it tests for a race condition which no longer exists. Maybe these tests are only supposed to test that no errors are raised?

**Comment by ernesto-jimenez** [comment]
@lolmaus 

> Maybe these tests are only supposed to test that no errors are raised?

Yes, is to avoid regressions returning errors.

I've lots to learn about TDD in ember, so I would be happy to see how you refactor the tests :)

**Comment by lolmaus** [comment]
@ernesto-jimenez, my take: https://github.com/lolmaus/ember-cli-async-button/commit/eba0ea12ccffe448b63fc7c857a2e176460f99f1
