### ISSUE TITLE
Handlebars error: Could not find component or helper

### ISSUE THREAD

**Issue by sbsurf** [dockyard/ember-cli-async-button#26]
Hi. I am trying to use the component in my template, after installing it via NPM.

```
  {{async-button action="save" default="Save" pending="Saving..."}}
```

However, when running the app, I get this error:

```
Uncaught Error: <my@view:search-map::ember831> Handlebars error: Could not find component or helper named 'async-button'
```

Any idea why?

**Comment by bcardarella** [comment]
what version of ember, ember-cli, handlebars, etc... ?

**Comment by sbsurf** [comment]
Ah, I suspect it's my Handlebars version?

```
DEBUG: Ember                     : 1.9.1
ember.js:3935 DEBUG: Ember Data                : 1.0.0-beta.14.1
ember.js:3935 DEBUG: Handlebars                : 2.0.0
ember.js:3935 DEBUG: jQuery                    : 1.11.2
```

**Comment by bcardarella** [comment]
what version of ember-cli ?

**Comment by sbsurf** [comment]
0.1.7

**Comment by rwjblue** [comment]
@sbsurf - How did you install?  Is `ember-cli-async-button` in your `package.json`?

**Comment by sbsurf** [comment]
Sorry guys. I guess I forgot to restart the app after running the install. Thanks for the quick help. Really appreciate it.

**Comment by rwjblue** [comment]
No problem, glad you got it fixed.
