### ISSUE TITLE
Passing actions parameters

### ISSUE THREAD

**Issue by jackmatt2** [dockyard/ember-cli-async-button#27]
I was about to convert a table of mine to use async-button.

The problem is that each button is part of an {{#each}} loop and the task is passed as an action parameter.

With a regular button
```javascript
{{#each task in tasks}}
      <button {{action "deleteTask" task}}>Delete</button>
```

With async-button there is no way to sypply the task to the action
```javascript
{{#each task in tasks}}
      <button {{action "deleteTask" task}}>Delete</button>
      {{async-button type="submit" action="deleteTask" default="Delete" pending="Deleting..." fulfilled="Delete" rejected="Failed. Try again"}}
 
```
Is there a way to support what I am trying to do?

**Comment by danmcclain** [comment]
You could have the body of the `each` be a component, which would handle the action itself

**Comment by bcardarella** [comment]
@danmcclain I believe he is talking about passing in each unique task item into the async button component.

**Comment by bcardarella** [comment]
@jackmatt2 you can do:

```javascript
{{#each task in tasks}}
      <button {{action "deleteTask" task}}>Delete</button>
      {{async-button type="submit" task=task action="deleteTask"}}
```

however the trick now is to get that property passed into the callback. @rwjblue thoughts?

**Comment by danmcclain** [comment]
I was suggesting the component as a work around, as it would create a local scope that the action would occur within, so you could retrieve the task of the component in the action of the component and not need to pass it to the action. Less than idea, but it should work

**Comment by fsmanuel** [comment]
@jackmatt2 what about `itemController` in the `each`?

**Comment by danmcclain** [comment]
@jackmatt2 This just landed in master:

```hbs
{{async-button model "another agrument" ... action="save" default="Save" pending="Saving..."}}
```
and the action function will be passed the arguments:
```js
 save: function(callback, firstArg, secondArg, ...) {
      var promise = this.get('model').save();

      callback(promise);

      promise.then(function() {
        ...
      });
    }
```
This will be in the next release once Ember-CLI 0.2.0 is released (currently a beta release), so if you want to use this, you'll need to update to that beta, and Ember 1.10 to use the master branch

**Comment by jackmatt2** [comment]
@danmcclain great thanks
