### ISSUE TITLE
Guarding against Ember.set on destroyed

### ISSUE THREAD

**Issue by jasonmit** [dockyard/ember-cli-async-button#30]
# Steps to reproduce:
* Go to http://jsbin.com/seruvepoyu/1/edit
* Click `save`
* Immediately after click `test`
* Wait for the assertion

I see this as a major downfall of passing around callbacks in actions, but I see this is something that is being encouraged now.  Is this going to be the official pattern going forward, and if it is should we just swallow the `calling set on destroyed object` assertion.

**Comment by danmcclain** [comment]
I'm on my phone right now, but is this not covered by https://github.com/dockyard/ember-cli-async-button/blob/master/addon/components/async-button.js#L60

I'm guessing that the promise is adjusting something other than the button if the above doesn't cover your issue


Sorry if I'm missing context, seeing if there is a quick answer

**Comment by jasonmit** [comment]
@danmcclain ah, then the demo needs to be updated.  Feel free to close.

**Comment by danmcclain** [comment]
The demo is pretty old. I just extended the API on master and should probably create a new demo once we release the next version. Thanks for noticing still!
