### ISSUE TITLE
Error: Missing template processor. Master is unusable.

### ISSUE THREAD

**Issue by lolmaus** [dockyard/ember-cli-async-button#33]
The master version of the addon is unusable for me.

Including 

```
    "ember-cli-async-button": "git://github.com/dockyard/ember-cli-async-button.git",
```

to `package.json` renders the app impossible to start. Running `ember s` results in an error "Missing template processor". [Stacktrace](https://gist.github.com/lolmaus/113b1027d27f7699d143).

This is reproducible on a fresh `ember new foo` project.

**Comment by bcardarella** [comment]
Very strange, TravisCI is passing. @rwjblue any idea what this is?

**Comment by bcardarella** [comment]
I just confirmed this with latest ember-cli (0.2.0-beta.1)

**Comment by bcardarella** [comment]
related: https://github.com/ember-cli/ember-cli/issues/3419

**Comment by bcardarella** [comment]
@lolmaus try master now

**Comment by lolmaus** [comment]
Will try later and report. Thank you, @bcardarella.

**Comment by lolmaus** [comment]
Still have the issue.

I did `rm -rf node_modules/ember-cli-async-button` and `npm install`.

`npm list | grep async-button` reports the latest commit on `master`:

    $ npm list | grep ember-cli-async-button
    ├── ember-cli-async-button@0.5.0 (git://github.com/dockyard/ember-cli-async-button.git#8fb2fc28ee6140a4f2a71669e746cb3d849b91cf)

So do `0.5.0` and `0.4.0` releases.

`0.3.1` works fine. All other addons in my project work fine.

:ambulance:

**Comment by rwjblue** [comment]
What version of Ember CLI are you running with?  0.4.0 and above requires ember-cli 0.2.0 or above.  I submitted https://github.com/dockyard/ember-cli-async-button/pull/36 to make sure a nice message is printed when using older Ember CLI versions.

**Comment by rwjblue** [comment]
I just tested 0.5.0 against an app using Ember CLI 0.2.0 and it does build properly...

**Comment by lolmaus** [comment]
I was on  `0.2.0-beta.1`. Upgrading to `0.2.0` resolved the issue. Thank you, @rwjblue.

**Comment by bcardarella** [comment]
:+1:
