### ISSUE TITLE
Callback is undefined

### ISSUE THREAD

**Issue by anthonycollini** [dockyard/ember-cli-async-button#39]
I can't get this plugin to work properly as `callback` is undefined.

Any thoughts as to why? This is specifically mentioned in the docs.

Ember 1.10.0
Ember Data 1.0.0-beta.16
Ember CLI 0.2.1
node: 0.12.0
npm: 2.7.3
jQuery 1.11.2

![screenshot 2015-04-07 17 02 47](https://cloud.githubusercontent.com/assets/933222/7033432/006a0bc4-dd48-11e4-96a5-7d5bba95adcb.png)

![screenshot 2015-04-07 17 02 35](https://cloud.githubusercontent.com/assets/933222/7033431/006a0c00-dd48-11e4-8c4b-01011e92c81f.png)

**Comment by bcardarella** [comment]
This is strange. Can you create a failing test for this or can you share code where this is happening?

**Comment by anthonycollini** [comment]
The issue was that it was a component within a component. Moving the async-button component out to the main template solved the issue. 

This made me look at the sendAction in my outermost component, and... I wasn't passing the callback along with sendAction.

`this.sendAction('save', callback);`
