### ISSUE TITLE
How to resolve button when there's no promise

### ISSUE THREAD

**Issue by samselikoff** [dockyard/ember-cli-async-button#40]
When I click a "save" async-button, I first check that the model is valid. If not, I show a message. All of this is sync, yet the async-button shows the "pending" state. How do I resolve this?

**Comment by danmcclain** [comment]
@samselikoff In the past, I've passed either `Ember.RSVP.reject()` or `Ember.RSVP.resolve()` to the callback, depending on what I was doing. In your case, I'd use `reject`, since you aren't in the correct state to resolve the action

**Comment by samselikoff** [comment]
Gotcha, thanks!
