### ISSUE TITLE
Any plans to support inline if for disabled property?

### ISSUE THREAD

**Issue by toranb** [dockyard/ember-cli-async-button#44]
At this time it looks like disabled won't allow a custom inline if that you pass in. Would this be something the team at dockyard would accept as a PR? If yes/no do you have another PR or issue someone has submitted in the past for reference? If this is new functionality completely -any suggestions for binding model properties for the disabled property **w/out having to add model as an attributeBinding and doing a custom binding like shown below?

```js
    initialize: Ember.on("init", function() {
        Ember.Binding.from("model.isDirty").to("thingWasDirty").connect(this);
    })
```

**Comment by rwjblue** [comment]
Can you provide a snippet of what you mean?

**Comment by williamsbdev** [comment]
@rwjblue we are trying to provide an initial disabled value for empty/non-dirty forms. Below is some code that we have "working" for our use case. We have not flushed out everything yet but is this something that might be of value to the project?

```js
 disabled: Ember.computed('textState', 'disabledOn', function() {
      var disabledOn = this.get('disabledOn');
      var textState = this.get('textState');
      if (disabledOn !== undefined) {
          return disabledOn;
      }
      if (textState === 'pending') {
          return true;
      }
      return false;
}),
```

```js
<div id="custom-disabled">
  {{input value=model.name}}
  {{async-button disabledOn=model.isDirty default="Save"}}
</div>
```

**Comment by toranb** [comment]
@rwjblue ignore my initialize snippet above. @williamsbdev was able to get it working w/out :)

**Comment by toranb** [comment]
We opened up a legit PR for this feature in #46
