### ISSUE TITLE
[QUESTION] no promise fired, how do prevent the "pending" state

### ISSUE THREAD

**Issue by williamsbdev** [dockyard/ember-cli-async-button#45]
I am trying to use this async-button component and I really like it.

I am running into an issue where my client side validation says that I do not need to fire an ajax request because I know that the form is not valid. I display my errors and forgo sending the request.

It looks something like this:

```js
actions: {
    save: function(callback) {
        if(this.get("valid")) {
            this.sendAction("onSave", callback);
            // promise fired in "onSave" action
        }
    }
}
```

In this else condition, there is no promise to resolve so the async-button remains in a "pending" state. 

Thanks!

**Comment by bcardarella** [comment]
Let me see if I understand the situation:

* your validations are promise based
* your validation promise has not resolved yet
* you want to skip the remote validation and just force a form submit
* because of this the async-button is stuck in `pending` state

Do I have the sequence of events correct?

**Comment by toranb** [comment]
The validations are promise based *if /and when* they are valid on the client. Until that is a truthy statement we don't want to fire the xhr. Because of this we get stuck as you described.

How do you work around this using your ember validation library on client projects?

**Comment by bcardarella** [comment]
@toranb ember-validations actually has the remote validators as part of the validation model. After the local validators complete the remote validators fire. When *all* validators are valid then the promise is completed.

**Comment by toranb** [comment]
Ah that's right - I do remember seeing that at some point. Thanks for the quick feedback!

**Comment by williamsbdev** [comment]
@bcardarella Thanks for following up on this! This makes a lot more sense when all validations are promise based.
