### ISSUE TITLE
[VERSION] will there be a new version published soon?

### ISSUE THREAD

**Issue by williamsbdev** [dockyard/ember-cli-async-button#55]
Thank you for this awesome open source project. I have been using this addon in my apps and have had some great success. However, I have noticed that there are some recent commits on master but there has not been a new publish on npm in 5 months. Will there be a new version published soon?

**Comment by rwjblue** [comment]
FYI - Master only works with Ember 1.13+. In general, we probably need to add an Ember version support matrix to the README to let folks know what versions to use for which Ember versions.

I'm :+1: on a release though (will likely need to be 0.6.0).

**Comment by bcardarella** [comment]
I'd like to have the library updated to ember-cli 1.13 just for sanity's sake before pulling the trigger on a release. Open to a PR for this

**Comment by williamsbdev** [comment]
I don't have time to work on this today but will try to get a PR up by Wednesday night.

Thanks!

**Comment by Dhaulagiri** [comment]
@bcardarella @williamsbdev see #56

**Comment by williamsbdev** [comment]
@Dhaulagiri I just upgraded to ember-cli 1.13.8 in my PR #46 because I did not see you had already done the work. @bcardarella Can we get either one or both of our PRs merged?

Thanks!

**Comment by bcardarella** [comment]
@williamsbdev just merged :)
